spring:
  application:
    name: local-cae-job-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:sqlite:${app.database-path}
    driver-class-name: org.sqlite.JDBC
  web:
    resources:
      static-locations: classpath:/static/

server:
  address: 127.0.0.1
  port: 8765

app:
  name: Local CAE Job Service
  database-path: data/jobs.db
  workspace-root: workspaces
  ansa-executable: 'C:\Program Files\BETA_CAE_Systems\ansa_v24.1.3\win64\ansa64.bat'
  ansa-script-file: 'C:\scripts\run_ansa.py'
  ansa-execpy-prefix: "load_script:"
  ansa-batch-flags:
    - -b
  allowed-origins:
    - http://127.0.0.1:3000
    - http://localhost:3000
  log-poll-interval-seconds: 0.5
  ansa-candidate-paths:
    - 'C:\Program Files\BETA_CAE_Systems\ansa_v24.1.3\win64\ansa64.bat'
    - 'C:\Program Files\BETA_CAE_Systems\ansa_v24.1.3\win64\ansa64.exe'
    - 'C:\BETA_CAE_Systems\ansa_v24.1.3\win64\ansa64.bat'
    - 'C:\BETA_CAE_Systems\ansa_v24.1.3\win64\ansa64.exe'

logging:
  level:
    root: INFO
